debug: false
enableTax: true
taxAccountUUID: 36aa1900-8daa-422b-827d-16a344707ee7
taxRate: 0.05
dataSource:
  driver: sqlite
  prefix: uis_
  url: jdbc:sqlite:plugins/UltimateInventoryShop/sqlite.db
  #
  # driver: mysql
  # prefix: uis_
  # url: jdbc:mysql://localhost:3306/minecraft
  # user: minecraft
  # password: minecraft
  #
  # driver: postgresql
  # prefix: uis_
  # url: jdbc:postgresql://localhost:5432/postgres
  # user: postgres
  # password: postgres
hikari:
  poolName: UISHikariCP
  minimumIdle: 10
  idleTimeout: 600000
  maximumPoolSize: 10
  maxLifetime: 1800000
  connectionTimeout: 30000
lang:
  prefix: '[uis] '
  price: 价格
  afterTax: 税后价格
  uisName: 箱子商店
  currentGoods: 当前商品
  seller: 卖家
  buyer: 买家
  myGoods: 我出售的
  myGoodsBeenSold: 我已卖出的
  pageIndexName: '当前页码: '
  previousPage: 上一页
  nextPage: 下一页
  emptyInMainHand: 手上没有东西
  sellUsage: /uis sell <价格> <描述>
  materialLoadError: 材料读取失败
  invalidItem: 购买失败，物品可能已经下架
  sellSuc: 出售成功
  sellFail: 出售失败
  sqlError: 数据库连接失败
  playerNotFound: 未找到玩家
  buyFail: 购买失败，物品可能已被他人购买
  buySuc: 购买成功
  noEnoughMoney: 余额不足
  invFull: 物品栏已满
  taxAccountError: 税收账户配置错误
  redeemSuc: 赎回成功
  redeemFail: 赎回失败
  cannotBuySelfGoods: 不能购买自己的商品
  notBelongToYou: 商品不属于你
material:
  pageIndexMaterial: PAPER
  previousPageMaterial: BIRCH_BUTTON
  nextPageMaterial: BIRCH_BUTTON
  currentGoods: DIAMOND
  myGoods: GRASS_BLOCK
  myGoodsBeenSold: GOLD_INGOT
