name: UltimateInventoryShop
version: 1.0.0-rc6
main: cat.kiwi.minecraft.uis.UltimateInventoryShopPlugin
load: STARTUP
authors: [ moeKiwiSAMA ]
description: UltimateShop
api-version: 1.19
depend: [Vault, NBTAPI]
softdepend: [PlaceholderAPI]
commands:
  uis:
    description: Ultimate Inventory Shop
    usage: 未找到经济插件(An economy plugin is required)