name: UltimateInventoryShop
version: 0.0.1
main: cat.kiwi.minecraft.uis.UltimateInventoryShopPlugin
load: STARTUP
authors: [ moeKiwiSAMA ]
description: UltimateShop
api-version: 1.19
depend: [Vault, NBTAPI]
softdepend: [PlaceholderAPI]
commands:
  uis:
    description: Ultimate Inventory Shop
    usage: /uis help
  ultimateinventoryshop:
    description: Ultimate Inventory Shop
    usage: /uis help